name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      name: 
        description: 'Just a name'
        required: true
        default: 'World'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ROS_CI_DESKTOP: "`lsb_release -cs`"
      ROS_DISTRO: noetic
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Download FavDish
        run: |
          cd ~/
          ssh-agent sh -c 'echo "${{ secrets.PRIVATE_DEPENDENCY }}" | ssh-add - && git clone git@github.com:tjovcheska/FavDish.git'
          cd FavDish
