name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      name: 
        description: 'Just a name'
        required: true
        default: 'World'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download Private Repository
        run: |
          git clone https://${{ secrets.PRIVATE_REPOSITORY }}@github.com/tjovcheska/FavDish.git
          cd FavFish
          ls -la
